#!/usr/bin/env bash

set -e
set -u
set -o pipefail

branch=""
tag=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -b|--branch)
            branch="$2"
        ;;
        -t|--tag)
            tag="$2"
        ;;
        *)
            break
        ;;
    esac
    shift 2
done

if [[ $branch && "$CIRCLE_BRANCH" != "$branch" ]]; then
    echo "Not on branch $branch. Skipping..."
    exit 0
fi

if [[ $tag && "$(git log -1 --pretty=%B)" != *\[$tag\]* ]]; then
    echo "No [$tag] commit tag found. Skipping..."
    exit 0
fi

echo "Checking for running builds..."

jq_filters=""

if [[ $branch ]]; then
    jq_filters+=" and .branch == \"$branch\""
fi

if [[ $tag ]]; then
    jq_filters+=" and (.subject | contains(\"[$tag]\")"
fi

jq_prog=".[] | select(.build_num < $CIRCLE_BUILD_NUM and (.status | test(\"running|pending|queued\")) $jq_filters) | .build_num"

url="https://circleci.com/api/v1/project/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?circle-token=$CIRCLE_TOKEN&limit=100"


while true; do
    builds=$(curl -s -H "Accept: application/json" "$url" | jq "$jq_prog")
    if [[ -z $builds ]]; then
        break
    else
        echo "Waiting on builds:"
        echo "$builds"
    fi
    echo "Retrying in 5 seconds..."
    sleep 5
done

echo "Acquired lock"

"${@}"
